[build.environment]
  NODE_VERSION = "18.18.0"

[build]
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
